service: feral-cats-example

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
functions: 
  routes:
    handler: index.http4sHandler
    events:
      - http:
          path: /foo
          method: get
      - http:
          path: /joke #Currently getting cpnnection refused on this endpoint, need to look into it
          method: get
