service: feral-cats-example

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
package:
  patterns:
    -target/scala-2.13/npm-package/**	
functions:
  hello:
    handler: index.http4sHandler
    events:
      - http:
          path: foo
          method: get
      - http:
          path: joke
          method: get