AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Environment:
      Variables:
        STAGE: !Ref Stage

Resources:        
  FeralCatsExample:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/scala-2.13/npm-package/
      Handler: index.http4sHandler
      Runtime: nodejs18.x
      MemorySize: 1024
      Timeout: 6
      Events:
        fooApi:
          Type: Api 
          Properties:
            Path: /foo
            Method: get
        jokeApi:
          Type: Api 
          Properties:
            Path: /joke
            Method: get