name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: sbt npmPackage
    - run: mv serverless.yml target/scala-2.13/npm-package/
    - run: cd target/scala-2.13/npm-package/ && npm install
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: -c "cd ./target/scala-2.13/npm-package/ && serverless deploy"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}